### ISSUE TITLE
Bugs when run examples (test_WDM_transmission)

### ISSUE THREAD

**Issue by Tonghui-Ji** [edsonportosilva/OptiCommPy#15]
Dear Sir, 
I encountered with some errors when runing examples 'test_WDM_transmission'. I tried to fix it, but failed. The main problems is in the function named equaliztion.coreAdaptEq. Here are the errrors during simulation:
1. It seems that the @njit dose not work on my PC.
![image](https://github.com/edsonportosilva/OptiCommPy/assets/49855704/eeddc67e-9207-4e29-a648-1d9f2b0e3952)
2. In order to fix this, I delelte @njit, then there comes other errors.
![image](https://github.com/edsonportosilva/OptiCommPy/assets/49855704/4e327270-6edf-4234-976f-8ae12b284a44)
In order to fix this, I use Hiter[:, :, 0] = H to replace Hiter[:, :, 1] = H
3. Another index error comes.
![image](https://github.com/edsonportosilva/OptiCommPy/assets/49855704/fa7040de-ab05-44ac-a640-15b7d2c14060)
Can you help me figure out this bug? Thanks a lot.

**Comment by edsonportosilva** [comment]
Hello @Tonghui-Ji. First, I believe you are having issues with the Numba installation on your PC. Please, make sure your PC is compatible and has Numba installed. Second, if you don't have Numba, you can still run the equalizers by removing the @njit decorator manually from the code, as you did. The only difference should be that the function will run more slowly. However, the non-Numba version of this code had a few bugs we have corrected recently. I have just updated the code in the repository with a new version where those bugs should be corrected, and you should be able to run it with or without @njit. Could you please update your code and try to rerun it (without @njit) to see if the problem is still there? Please note that, after the update, the way other functions are called has also been changed, such that it may break the code of old notebooks you may have been using. If you run the new 'test_WDM_transmission.ipynb' in the repository, you should see no errors. Let me know if the problem persists.

**Comment by Tonghui-Ji** [comment]
Great! Thanks a lot for your quick response. 
The errors had been fixed with the latest version without @njit.
However, Numba still does not work on my PC and report the same error as above. I had also reinstall the numba. Could you share the exact version of python and numba you used? I will make a double check of this problem. Thanks again!

**Comment by edsonportosilva** [comment]
Currently, I am running it with Numba 0.57.1, but it should work with >=0.54.1.
